use_frameworks!

platform :ios, '10.0'

target 'GJResourceSelector_Example' do
  pod 'GJResourceSelector', :path => '../'

  target 'GJResourceSelector_Tests' do
    inherit! :search_paths

    
  end
end
